# 47장 에러 처리

# 에러 처리의 필요성

에러는 언제든지 발생할 수 있으며, 적절히 처리하지 않으면 프로그램은 강제 종료된다. `try...catch`문을 사용하여 에러에 대응하면 프로그램이 종료되지 않고 계속 실행될 수 있다.

```js
try {
  foo();
} catch (error) {
  console.error("[에러 발생]", error);
}
```

## try...catch...finally 문

에러 처리 방식에는 조건문을 통한 확인과, 에러 처리 코드를 미리 등록하는 방식이 있다. `try...catch...finally` 문은 에러 처리 코드를 등록하는 방식으로, 세 개의 코드 블록으로 구성된다. `finally`는 생략 가능하다.

```js
try {
  // 실행 코드
} catch (err) {
  // 에러 처리 코드
} finally {
  // 생략 가능
}
```

## Error 객체

`Error` 생성자 함수는 에러 객체를 생성한다. 이 에러 객체는 `message`와 `stack` 프로퍼티를 포함하며, 자바스크립트는 7가지 에러 객체 생성자를 제공한다.

```js
const error = new Error("invalid");
console.log(error.message); // 'invalid'
```

### 주요 에러 객체

- `SyntaxError`: 문법 오류
- `ReferenceError`: 참조 불가 식별자
- `TypeError`: 잘못된 데이터 타입
- `RangeError`: 범위 초과 값

## throw 문

에러 객체를 생성만 해서는 에러가 발생하지 않으며, `throw`문으로 에러 객체를 던져야 한다.

```js
try {
  throw new Error("something wrong");
} catch (error) {
  console.log(error);
}
```

## 에러 전파

에러는 호출자 방향으로 전파된다. 에러가 발생하면 해당 에러는 호출 스택을 따라 상위 함수로 전달되며, 적절히 캐치되지 않으면 프로그램은 종료된다.

```js
const foo = () => {
  throw Error("foo에서 발생한 에러");
};
try {
  foo();
} catch (err) {
  console.error(err);
}
```
