### 1. 제너레이터란?

ES6에서 도입된 제너레이터는 코드 블록의 실행을 일시 중지했다가 필요한 시점에서 재개할 수 있는 특수한 함수다.

- 제너레이터 함수는 함수 호출자에게 함수 실행의 제어권을 양도할 수 있다.
    
    일반 함수 호출 시 제어권이 함수에게 넘어가고 함수 코드가 실행된다. 
    
    제너레이터 함수는 함수 실행을 함수 호출자가 제어할 수 있는데 함수 호출자가 함수 실행을 일시 중지하거나 재개시킬 수 있다. 
    
    함수의 제어권을 함수가 독점하는 것이 아니라 함수 호출자에게 양도할 수 있다는 것을 의미한다.
    
- 제너레이터 함수는 함수 호출자와 함수의 상태를 주고받을 수 있다.
    
    일반 함수 호출 시 매개변수를 통해 함수 외부에서 값을 받고 함수 코드를 시행해 결과를 함수 외부로 반환한다. 
    
    즉 함수가 실행되는 동안에는 함수 내부로 값을 전달해 함수 상태를 변경할 수 없다. 
    
    제너레이터 함수는 함수 호출자와 양방향으로 함수 상태를 주고받을 수 있다. 
    
    제너레이터 함수는 함수 호출자에게 상태를 전달할 수 있고 함수 호출자로부터 상태를 전달받을 수도 있다.
    

### 2. 제너레이터 함수의 정의

제너레이터 함수는 function* 키워드로 선언한다. 그리고 하나 이상의 yield 표현식을 포함한다.

```jsx
// 제너레이터 함수 선언문
function* genDecFunc() {
    yield 1;
}

// 제너레이터 함수 표현식
const genExpFunc = function* () {
    yield 1;
};

// 제너레이터 메서드
const obj = {
    * genObjMethod() {
        yield 1;
    }
};

// 제너레이터 클래스 메서드
class MyClass {
    * genClsMethod() {
        yield 1;
    }
}
```


### 3. 제너레이터 객체

**제너레이터 함수를 호출**하면 일반 함수처럼 함수 코드 블록을 실행하는 것이 아니라 **제너레이터 객체를 생성해 반환**한다. 

**제너레이터 함수가 반환한 제너레이터 객체는 이터러블이면서 동시에 이터레이터**다.

```jsx
// 제너레이터 함수
function* genFunc() {
    yield 1;
    yield 2;
    yield 3;
}

// 제너레이터 함수를 호출하면 제너레이터 객체를 반환한다.
const generator = genFunc();

// 제너레이터 객체는 이터러블이면서 동시에 이터레이터다.
// 이터러블은 Symbol.iterator 메서드를 직접 구현하거나 프로토타입 체인을 통해 상속받은 객체다.
console.log(Symbol.iterator in generator); // true
// 이터레이터는 next 메서드를 갖는다.
console.log('next' in generator); // true
```


### 6. async/await

제너레이터를 비동기 처리를 동기 처리처럼 동작하도록 구현하면 사용하면 코드가 장황해지고 가독성도 좋지않다. 

ES8에서는 보다 간단하고 가독성 좋게 비동기 처리를 동기 처리처럼 동작하도록 구현할 수 있는 async/await가 도입되었다.

async/await 프로미스 기반으로 동작한다. 

then/catch/finally 후속 처리 메서드에 콜백함수를 전달해 비동기 처리 결과를 후속 처리할 필요 없이 동기 처리처럼 프로미스를 사용할 수 있다.

```jsx
const fetch = require('node-fetch');

async function fetchTodo() {
    const url = 'https://jsonplaceholder.typicode.com/todos/1';

    const response = await fetch(url);
    const todo = await response.json();
    console.log(todo);
    // {userId: 1, id: 1, title: 'delectus aut autem', completed: false}
}

fetchTodo();
```


### 6-3 에러 처리

비동기 처리를 위한 콜백 패턴의 단점 중 가장 심각한 것은 에러 처리가 곤란하다는 것이다.

async/await에서 에러 처리는 try … catch문을 사용할 수 있다.

```jsx
const fetch = require('node-fetch');

const foo = async () => {
    try {
        const wrongUrl = 'https://wrong.url';

        const response = await fetch(wrongUrl);
        const data = await response.json();
        console.log(data);
    } catch (err) {
        console.error(err); // TypeError: Failed to fetch
    }
};

foo();
```